config/routes.rb
Rails.application.routes.draw do

  root 'welcome#index'

  resources :passwords, controller: "clearance/passwords", only: [:create, :new]
  resource :session, controller: "clearance/sessions", only: [:create]

  resources :users, controller: "clearance/users", only: [:create] do
    resource :password,
      controller: "clearance/passwords",
      only: [:create, :edit, :update]
  end

  get "/sign_in" => "clearance/sessions#new", as: "sign_in"
  delete "/sign_out" => "clearance/sessions#destroy", as: "sign_out"
  get "/sign_up" => "clearance/users#new", as: "sign_up"

  get "/auth/:provider/callback" => "sessions#create_from_omniauth"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :users, controller: "users", only: [:show, :edit, :update]

  resources :listings do
    resources :bookings, only: [:create]
  end

  resources :bookings, only: [:destroy]
end

app/models/listing.rb
class Listing < ApplicationRecord
  belongs_to :user
  has_many :taggings, dependent: :destroy
  has_many :tags, through: :taggings
  has_many :bookings
  mount_uploaders :pictures, PictureUploader
  serialize :pictures, Array


	def all_tags=(names)
  		self.tags = names.split(",").map do |name|
  		Tag.where(name: name.strip).first_or_create!
  		end
  	end

  	def all_tags
  		self.tags.map(&:name).join(", ")
  	end
  	
end

app/controllers/listings_controller.rb
class ListingsController < ApplicationController
	before_action :find_listing, only: [:show, :edit, :update, :destroy]
	before_action :check_owner, only: [:edit, :update, :destroy]

	def index
    	@listings = Listing.order("created_at DESC")
  	end

	def show
		@booking = @listing.bookings.new
	end

	def new

	end

	def create
		@listing = current_user.listings.new(listing_params)
		
		if @listing.save
			redirect_to @listing 
		else 
			render :new 
		end 
	end

	def edit
		
	end

	def update
		
		if @listing.update(listing_params)
			redirect_to @listing
		else
			render :edit
		end
	end

	def destroy
		
		@listing.destroy
		redirect_to listings_path
	end

private

	def listing_params
		params.require(:listing).permit(:title, :description, :location, :all_tags, 
			:price, :country, :country_code, :property_type, :max_guests, pictures: [])
	end

	def find_listing
		@listing = Listing.find(params[:id])
	end

	def check_owner
		@listing = Listing.find(params[:id])
		if @listing.user != current_user
		redirect_to listings_path
		end	
	end

end

app/helpers/listings_helper.rb
module ListingsHelper
end

app/views/listings/edit.html.erb
<h1>Edit Your Listing</h1>
<br>

<div class="form-horizontal">
<%= form_for @listing, url: listing_path do |f| %>

  <div class="form-group">
    <%= f.label :title, :class => 'col-sm-2 control-label' %>
    <div class="col-sm-8">
      <%= f.text_field :title, :class => 'form-control' %>
    </div>
  </div>

  <div class="form-group">
    <%= f.label :location, :class => 'col-sm-2 control-label' %>
    <div class="col-sm-8">
      <%= f.text_field :location, :class => 'form-control' %>
    </div>
  </div>

  <div class="form-group">
    <%= f.label :price, :class => 'col-sm-2 control-label' %>
    <div class="col-sm-8">
      <%= f.text_field :price, :class => 'form-control' %>
    </div>
  </div>

    <div class="form-group">
      <%= f.label :property_type, :class => 'col-sm-2 control-label' %>
      <div class="col-sm-8">
        <%= f.select :property_type, options_for_select(["House","Apartment","Condominium","Townhouse","Bungalow"]), {}, :class => "form-control" %>
      </div>
    </div>

    <div class="form-group">
      <%= f.label :max_guests, :class => 'col-sm-2 control-label' %>
      <div class="col-sm-8">
        <%= f.select :max_guests, options_for_select(["1","2","3","4","5","6","7","8","9","10"]), {}, :class => "form-control" %>
      </div>
    </div>

  <div class="form-group">
    <%= f.label :description, :class => 'col-sm-2 control-label' %>
    <div class="col-sm-8">
        <%= f.text_area :description, :class => 'form-control', :rows => '5' %>
      </div>
    </div>
    
    <div class="form-group">
      <%= f.label :tag, :class => 'col-sm-2 control-label' %>
      <div class="col-sm-8">
        <%= f.text_field :all_tags, placeholder: "Tags separated with comma", :class => 'form-control' %>
      </div>
    </div>

      <div class="form-group">
    <%= f.label :pictures, :class => 'col-sm-2 control-label' %>
    <div class="col-sm-8">
      <%= f.file_field :pictures, multiple: true, :class => 'form-control' %>
    </div>
  </div>


  <div class="form-group">
    <div class="col-sm-offset-2 col-sm-8">
      <%= f.submit :class => 'btn btn-primary' %>
    </div>
  
<% end %>
</div>

app/views/listings/index.html.erb
    <div class="container">
        <div class="row">
            <!-- Blog Entries Column -->
            <div class="col-md-8">
            <% @listings.each do |listing| %>
                <h1 class="page-header">
                    <%= listing.title %>
                    <small>From RM<%= listing.price %> per night</small>
                </h1>

                <!-- First Blog Post -->
                <h2>
                    Location: <small><%= listing.location %></small>
                </h2>
                <p class="lead">
                    Hosted by <%= listing.user.name %>
                </p>
                <p><span class="glyphicon glyphicon-time"></span> Posted on <%= listing.created_at.strftime('%d %B %Y')  %></p>
                <hr>
                <%= image_tag listing.pictures.first, :alt => "rss feed", :class => "img-responsive"  %>
                <hr>
                <p><%= listing.all_tags%></p>
                <button class="btn btn-default"><%= link_to 'Find Out More', listing_path(listing) %><span class="glyphicon glyphicon-chevron-right"></span></button>
                <br></br>
                <% end %>
                <hr>

                <!-- Pager -->
                <ul class="pager">
                    <li class="previous">
                        <a href="#">&larr; Older</a>
                    </li>
                    <li class="next">
                        <a href="#">Newer &rarr;</a>
                    </li>
                </ul>

            </div>
        </div>
      </div>

app/views/listings/new.html.erb
<h1>Hi, <%= current_user.name %>! Let's get started listing your space.</h1>
<br>
<div class="form-horizontal">
<%= form_for :listing, url: listings_path do |f| %>

  <div class="form-group">
    <%= f.label :title, :class => 'col-sm-2 control-label' %>
    <div class="col-sm-8">
      <%= f.text_field :title, :class => 'form-control' %>
    </div>
  </div>

  <div class="form-group">
    <%= f.label :location, :class => 'col-sm-2 control-label' %>
    <div class="col-sm-8">
      <%= f.text_field :location, :class => 'form-control' %>
    </div>
  </div>

  <div class="form-group">
    <%= f.label :price, :class => 'col-sm-2 control-label' %>
    <div class="col-sm-8">
      <%= f.text_field :price, :class => 'form-control' %>
    </div>
  </div>

    <div class="form-group">
      <%= f.label :property_type, :class => 'col-sm-2 control-label' %>
      <div class="col-sm-8">
        <%= f.select :property_type, options_for_select(["House","Apartment","Condominium","Townhouse","Bungalow"]), {}, :class => "form-control" %>
      </div>
    </div>

    <div class="form-group">
      <%= f.label :max_guests, :class => 'col-sm-2 control-label' %>
      <div class="col-sm-8">
        <%= f.select :max_guests, options_for_select(["1","2","3","4","5","6","7","8","9","10"]), {}, :class => "form-control" %>
      </div>
    </div>

  <div class="form-group">
    <%= f.label :description, :class => 'col-sm-2 control-label' %>
    <div class="col-sm-8">
        <%= f.text_area :description, :class => 'form-control', :rows => '5' %>
      </div>
    </div>
    
    <div class="form-group">
      <%= f.label :tag, :class => 'col-sm-2 control-label' %>
      <div class="col-sm-8">
        <%= f.text_field :all_tags, placeholder: "Tags separated with comma", :class => 'form-control' %>
      </div>
    </div>

      <div class="form-group">
    <%= f.label :pictures, :class => 'col-sm-2 control-label' %>
    <div class="col-sm-8">
      <%= f.file_field :pictures, multiple: true, :class => 'form-control' %>
    </div>
  </div>

  </div>
  <div class="form-group">
    <div class="col-sm-offset-2 col-sm-8">
      <%= f.submit :class => 'btn btn-primary' %>
    </div>
  
<% end %>
</div>

app/views/listings/show.html.erb
    <div class="container">
        <div class="row">
            <!-- Blog Entries Column -->
            <div class="col-md-8">

                <h1 class="page-header">
                    <%= @listing.title %>
                    <small>From RM<%= @listing.price %> per night</small>
                </h1>

               <div id="myCarousel" class="carousel slide" data-ride="carousel">
                <!-- Indicators -->
                  <ol class="carousel-indicators">
                    <li data-target="#myCarousel" data-slide-to="0" class="active"></li>
                    <li data-target="#myCarousel" data-slide-to="1"></li>
                    <li data-target="#myCarousel" data-slide-to="2"></li>
                  </ol>

                  <!-- Wrapper for slides -->
                  <div class="carousel-inner">
                    <div class="item active">
                      <%= image_tag @listing.pictures.first.thumb, class: "img-responsive" %>
                    </div>
                  <% @listing.pictures.shift %>  
                  <% @listing.pictures.each do |picture| %>
                    <div class="item">
                      <%= image_tag picture.thumb, class: "img-responsive" %>
                    </div>
                    <% end %>
                  </div>

                  <!-- Left and right controls -->
                  <a class="left carousel-control" href="#myCarousel" data-slide="prev">
                    <span class="glyphicon glyphicon-chevron-left"></span>
                    <span class="sr-only">Previous</span>
                  </a>
                  <a class="right carousel-control" href="#myCarousel" data-slide="next">
                    <span class="glyphicon glyphicon-chevron-right"></span>
                    <span class="sr-only">Next</span>
                  </a>
                </div>
                <hr>
                <%# image_tag("property1.jpg", :alt => "rss feed", :class => "img-responsive") %>
                <hr>
                <h3>
                    Location: <small><%= @listing.location %></small>
                </h3>
                <p class="lead">
                    Hosted by <%= @listing.user.name %>
                </p>
                <p><span class="glyphicon glyphicon-time"></span> Posted on <%= @listing.created_at.strftime('%d %B %Y') %></p>
                <h3>
                	About this listing: <small><%= @listing.description %></small>
                </h3>

                <h3>
                	Property type: <small><%= @listing.property_type %></small>
                </h3>

                <h3>
                	Accomodates: <small><%= @listing.max_guests %></small>
                </h3>

                <p><%= @listing.all_tags%></p>
                <% if @listing.user == current_user %>
      			<button class="btn btn-default"><span class="glyphicon glyphicon-pencil"></span><%= link_to ' Edit', edit_listing_path(@listing) %></button>
     			<button class="btn btn-default"><span class="glyphicon glyphicon-trash"></span><%= link_to ' Delete', listing_path(@listing), method: :delete, data: { confirm: 'Are you sure?'} %>
      			<% end %>
      			</button>
                <h3>Book Now</h3>
                <% if @errors.present? %>
                <div>
                <%= @errors %>
                </div>
                <% end %>
                <%= render "bookings/form" %>
                
                <hr>
                <h3><%= link_to 'All Listing', listings_path %></h3>
            </div>
        </div>
      </div>