config/routes.rb
Rails.application.routes.draw do

  root 'welcome#index'

  resources :passwords, controller: "clearance/passwords", only: [:create, :new]
  resource :session, controller: "clearance/sessions", only: [:create]

  resources :users, controller: "clearance/users", only: [:create] do
    resource :password,
      controller: "clearance/passwords",
      only: [:create, :edit, :update]
  end

  get "/sign_in" => "clearance/sessions#new", as: "sign_in"
  delete "/sign_out" => "clearance/sessions#destroy", as: "sign_out"
  get "/sign_up" => "clearance/users#new", as: "sign_up"

  get "/auth/:provider/callback" => "sessions#create_from_omniauth"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :users, controller: "users", only: [:show, :edit, :update]

  resources :listings do
    resources :bookings, only: [:create]
  end

  resources :bookings, only: [:destroy]
end

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-inverse">
  <div class="container-fluid">
  <div class="navbar-header">
      <a class="navbar-brand" href="localhost:3000">Pairbnb</a>
  </div>    
  <ul class="nav navbar-nav">
    <li id="hover"><%= link_to "Homes", listings_path %></li>
    <% if signed_in? %>
    <li id="hover"><%= link_to "Profile", user_path(current_user) %></li>
    <li id="hover"><%= link_to "Be a Host", new_listing_path %></li>
    <li id="hover"><%= link_to "Sign out", sign_out_path, method: :delete %></li> 
    <% else %>
    <li id="hover"><%= link_to "Login", sign_in_path %></li>
    <li id="hover"><%= link_to "Signup", sign_up_path %></li>
    <li id="hover"><%= link_to "Login with Facebook", "/auth/facebook" %></li>
    <% end %>
    <li id="hover"><%= link_to "About Us", root_url %></li>
  </ul>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Pairbnb</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => 'reload' %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => 'reload' %>
  <%= csrf_meta_tags %>
  <link href='https://fonts.googleapis.com/css?family=Open+Sans' rel='stylesheet' type='text/css'>
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
</head>
<body>
<%= render partial: "layouts/navbar" %>

<div class="container-fluid text-center">    
  <div class="row content">
    <div class="col-sm-2 sidenav">
      <p><a href="#">Homes</a></p>
      <p><a href="#">Experiences</a></p>
      <p><a href="#">Featured Destinations</a></p>
    </div>
    <div class="col-sm-8 text-left"> 

 <%= yield %>

    </div>
  </div>
</div>
<br></br>
<nav class="navbar">
    <div class="container center">
        <p>Company 2013. All Rights Reserved.</p>
    </div>
</nav>

</body>
</html>